# Generated by Django 3.1 on 2020-08-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookedDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='추가 일시')),
                ('day', models.DateField()),
            ],
            options={
                'verbose_name': '예약일',
                'verbose_name_plural': '예약일',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='추가 일시')),
                ('status', models.CharField(choices=[('진행중', '진행중'), ('확정', '확정'), ('취소', '취소')], default='진행중', max_length=32, verbose_name='상태')),
                ('check_in', models.DateField(verbose_name='체크인')),
                ('check_out', models.DateField(verbose_name='체크아웃')),
            ],
            options={
                'verbose_name': '예약',
                'verbose_name_plural': '예약',
            },
        ),
    ]
