# Generated by Django 3.1 on 2020-08-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='추가 일시')),
                ('name', models.CharField(max_length=80, verbose_name='이름')),
            ],
            options={
                'verbose_name': '목록',
                'verbose_name_plural': '목록',
            },
        ),
    ]
